version: "3.7"
services:
  web-server:
    build:
      context: .
      dockerfile: php.Dockerfile
    restart: always
    volumes:
      - "./html/:/var/www/html/"
      - "./modsecurity:/etc/modsecurity.d"
    ports:
      - "8080:80"

  mysql-server:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: mypass
    ports:
      - "9000:80"

volumes:
  mysql-data:
